# Generated by Django 3.1.1 on 2020-11-07 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmName', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['farmName'],
            },
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='valveDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valveNumber', models.CharField(max_length=10)),
                ('valveType', models.CharField(choices=[('1', 'drain valve'), ('2', 'zone valve')], default='1', max_length=1)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'valveNumber'],
            },
        ),
        migrations.CreateModel(
            name='valveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BooleanField(default=False)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.valvedevice')),
            ],
        ),
        migrations.CreateModel(
            name='soilHumidSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='soilHumidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(max_length=255)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.soilhumidsensor')),
            ],
        ),
        migrations.CreateModel(
            name='relayDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relayNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'relayNumber'],
            },
        ),
        migrations.CreateModel(
            name='relayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BooleanField(default=False)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.relaydevice')),
            ],
        ),
        migrations.CreateModel(
            name='flowSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='flowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BooleanField(default=False)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.flowsensor')),
            ],
        ),
        migrations.CreateModel(
            name='boardTempSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='boardTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(max_length=255)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.boardtempsensor')),
            ],
        ),
        migrations.CreateModel(
            name='boardHumidSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='boardHumidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(max_length=255)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.boardhumidsensor')),
            ],
        ),
        migrations.CreateModel(
            name='airTempSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='airTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(max_length=255)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.airtempsensor')),
            ],
        ),
        migrations.CreateModel(
            name='airHumidSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNumber', models.CharField(max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.farm')),
            ],
            options={
                'ordering': ['farm', 'sensorNumber'],
            },
        ),
        migrations.CreateModel(
            name='airHumidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(max_length=255)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFarm.airhumidsensor')),
            ],
        ),
    ]
