# Generated by Django 3.1.1 on 2020-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmCode',
            field=models.CharField(default='AA0001', max_length=255),
            preserve_default=False,
        ),
    ]
